# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        # the name of the "filter set"
        user_profile :
            quality : 100
            # list of transformations to apply (the "filters")
            filters :
                thumbnail  : { size : [24, 24], mode : outbound }
                upscale: { min: [24, 24] }